# yaml-language-server: $schema=https://raw.githubusercontent.com/mfontanini/presenterm/master/config-file-schema.json
defaults:
  theme: tokyonight-storm
  # override the terminal font size when in windows or when using sixel.
  terminal_font_size: 16

  max_rows: 100
  max_columns: 150
  # Valid values: top, center, bottom
  max_rows_alignment: center
  # Valid values: left, center, right
  max_columns_alignment: center

  list_item_newlines: 2

options:
  # whether slides are automatically terminated when a slide title is found.
  implicit_slide_ends: false

  # the prefix to use for commands.
  command_prefix: ""

  # show all lists incrementally, by implicitly adding pauses in between elements.
  incremental_lists: false

  # this option tells presenterm you don't care about extra parameters in
  # presentation's front matter. This can be useful if you're trying to load a
  # presentation made for another tool
  strict_front_matter_parsing: true

  # whether to treat a thematic break as a slide end.
  end_slide_shorthand: true
