#!/bin/sh
set -e

redirect() {
        exec </dev/null 1>&0 2>&0
}

fork() {
        exec setsid -f -- "$@"
}

spawn() {
        redirect
        if [ "$(uname)" = "Darwin" ]; then
                open -a "$@"
        else
                fork "$@"
        fi
}

if [ -n "$OPENER_CHOOSE" ]; then
        choose() {
                printf '%s\0' "$@" | fzf --read0 --no-sort --phony --layout=reverse
        }
else
        choose() {
                printf '%s' "$1"
        }
fi

case "$1" in
*.7z | *.a | *.ace | *.alz | *.arc | *.arj | *.bz | *.bz2 | *.cab | *.cpio | *.deb | *.gz | *.jar | \
        *.lha | *.lrz | *.lz | *.lzh | *.lzma | *.lzo | *.rar | *.rpm | *.rz | *.t7z | *.tar | *.tbz | \
        *.tbz2 | *.tgz | *.tlz | *.txz | *.tZ | *.tzo | *.war | *.xz | *.Z | *.zip)
        for file; do
                aunpack -- "$file"
        done
        ;;
*.[1-8])
        exec man -- "$@"
        ;;
*.pdf | *.ps | *.eps | *.djvu | *.djv | *.epub | *.cb[zr7t])
        exec zathura -- "$@"
        ;;
*.csv | *.tsv | *.sc | *.xlsx)
        case "$(choose sc-im editor libreoffice OnlyOffice)" in
        sc-im) exec sc-im -- "$@" ;;
        editor) exec $EDITOR -- "$@" ;;
        OnlyOffice) spawn OnlyOffice "$@" ;;
        libreoffice) spawn libreoffice "$@" ;;
        *) exit ;;
        esac
        ;;
*.od[cbdfgipstm] | *.odft | *.ot[cgipsth] | *.do[ct] | *.do[ct]x | *.p[po]t | *.p[po]tx | \
        *.xl[st] | *.xl[st]x)
        case "$(choose libreoffice OnlyOffice)" in
        OnlyOffice) spawn OnlyOffice "$@" ;;
        libreoffice) spawn libreoffice "$@" ;;
        *) exit ;;
        esac
        ;;
*.htm | *.html | *.xhtml)
        case "$(choose lynx firefox)" in
        lynx) exec lynx -- "$@" ;;
        firefox)
                first="true"
                for file; do
                        if [ -n "$first" ]; then
                                first=""
                                set -- "file://$file"
                        else
                                set -- "$@" "file://$file"
                        fi
                done
                spawn firefox -- "$@"
                ;;
        *) exit ;;
        esac
        ;;
*.svg)
        case "$(choose inkview inkscape)" in
        inkview) spawn inkview -- "$@" ;;
        inkscape) spawn inkscape -- "$@" ;;
        *) exit ;;
        esac
        ;;
*.mid | *.midi)
        exec fluidsynth -a alsa -m alsa_seq -l -i /usr/share/soundfonts/FluidR3_GM.sf2 -- "$@"
        ;;
*.cue)
        case "$(choose mpvc mpv)" in
        mpvc) spawn mpvc playlist add "$@" ;;
        mpv) exec mpv --no-audio-display -- "$@" ;;
        *) exit ;;
        esac
        ;;
*.swf)
        spawn sh -c '
      for file; do
        flashplayer "$file"
      done' \
                flashplayer "$@"
        ;;
esac

case "$(file -Lb --mime-type -- "$1")" in
image/*)
        case "$(choose gimp mvi)" in
        gimp) spawn gimp -- "$@" ;;
        mvi) exec mvi -- "$@" ;;
        *) exit ;;
        esac
        ;;
audio/* | */ogg)
        case "$(choose mpvc mpv)" in
        mpvc) spawn mpvc playlist add "$@" ;;
        mpv) exec mpv --no-audio-display -- "$@" ;;
        *) exit ;;
        esac
        ;;
video/*)
        case "$(choose iina mpv)" in
        iina) exec iina -- "$@" ;;
        mpv) exec mpv -- "$@" ;;
        *) exit ;;
        esac
        ;;
*)
        case "$(choose editor pager)" in
        editor) exec $EDITOR -- "$@" ;;
        pager) exec $PAGER -- "$@" ;;
        *) exit ;;
        esac
        ;;
esac
