#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.
if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS"; then
    eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi
mpd &                   # music player daemon-you might prefer it as a service though
remaps &                # run the remaps script, switching caps/esc and more; check it for more info
setbg &                 # set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources
# xcompmgr &              # xcompmgr for transparency
dunst &                 # dunst for notifications
xset r rate 300 50 &	# Speed xrate up
unclutter &		        # Remove mouse when idle
clipmenud &		        # Enables clipmenu, clipboard manager
maestral start &        # Enables dropbox on boot
syncthing &             # Enables syncthing web

# This line autostarts an instance of Pulseaudio that does not exit on idle.
# This is "necessary" on Artix due to a current bug between PA and
# Chromium-based browsers where they fail to start PA and use dummy output.
pidof -s runit &&
	pidof -s ! pidof -s pulseaudio >/dev/null 2>&1 &&
	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1
