#!/usr/bin/env bash

set -x

# ====== Variables =============================

declare -A gaps
declare -A color

gaps["top"]="4"
gaps["bottom"]="4"
gaps["left"]="4"
gaps["right"]="4"
gaps["inner"]="4"

# These are alpha colors, need to append two more character before the hex code, from 00 to FF for transaparancy
color["focused"]="0xE0ca56eb"
color["normal"]="0x00010101"
color["preselect"]="0xE02d74da"

# Debugging
# view the last lines of the error and debug logs, use below commands:
#   tail -f /tmp/yabai_$USER.err.log
#   tail -f /tmp/yabai_$USER.out.log
yabai -m config debug_output off

# Uncomment to refresh ubersicht widget on workspace change
# Make sure to replace WIDGET NAME for the name of the ubersicht widget
#ubersicht_spaces_refresh_command="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"WIDGET NAME\"'"

# ===== Loading Scripting Additions ============

# See: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# ===== Tiling setting =========================
# Layouts : bsp/stack/float
yabai -m config layout                      bsp
# Default layout per space
yabai -m config --space 1 layout stack
yabai -m config --space 2 layout stack
yabai -m config --space 3 layout stack


yabai -m config top_padding                 "${gaps["top"]}"
yabai -m config bottom_padding              "${gaps["bottom"]}"
yabai -m config left_padding                "${gaps["left"]}"
yabai -m config right_padding               "${gaps["right"]}"
yabai -m config window_gap                  "${gaps["inner"]}"

yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         off

yabai -m config window_topmost              off
yabai -m config window_opacity              off
yabai -m config window_shadow               float

yabai -m config window_border               on
yabai -m config window_border_width         2
yabai -m config active_window_border_color  "${color["focused"]}"
yabai -m config normal_window_border_color  "${color["normal"]}"
yabai -m config insert_feedback_color       "${color["preselect"]}"
yabai -m config window_border_blur off

yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.90
yabai -m config split_ratio                 0.50

yabai -m config auto_balance                off

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

# ===== Rules ==================================
# Floating window required SIP to be disabled
# https://github.com/koekeishiya/yabai/issues/527
# grid=<rows>:<cols>:<start-x>:<start-y>:<width>:<height>
yabai -m rule --add title="^(Notes|Scratchpad|Bottom|Ncmpcpp)$" app="^kitty$" manage=off layer=above sticky=on grid="10:16:7:5:16:10"
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="macfeh" app="^macfeh$" manage=off
# yabai -m rule --add label="System Settings" app="^System Settings" title=".*" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add label="Alfred Preferences" app="^Alfred Preferences$" title=".*" manage=off
yabai -m rule --add app="Raycast" title=".*" manage=off
yabai -m rule --add app="Maccy" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="KeePassXC" app="^KeePassXC$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add app="System Information" manage=off
yabai -m rule --add app="Slack" level!=0 border=off
yabai -m rule --add app="^Notification Centre$" manage=off
yabai -m rule --add app="^VLC$" title!="^(|Fullscreen Controls)$" manage=off

# Moves the apps to specific space
yabai -m rule --add title="^(Code)$" app="^kitty$" space=1
yabai -m rule --add title="^(Servers)$" app="^kitty$" space=2
yabai -m rule --add title="^(Postman|Databases)$" app="^kitty$" space=3
yabai -m rule --add app="^(Brave Browser|Google Chrome|Firefox|Microsoft Edge|Safari)$" space=4
yabai -m rule --add app="^(Slack|WhatsApp|Microsoft Teams|Telegram)$" space=5
yabai -m rule --add app="^(Twitch Studio)$" space=8
yabai -m rule --add app="^(VLC)$" space=9

# ===== Signals ================================

# Signal to focus on active widnow when a window is closed or minimized
# https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#67-signal
yabai -m signal --add event=application_launched action="~/.config/yabai/scripts/signals/application_launched.sh"
yabai -m signal --add event=application_terminated action="bash ~/.config/yabai/scripts/application_terminated.sh"
yabai -m signal --add event=window_created action="bash ~/.config/yabai/scripts/signals/window_created.sh"
yabai -m signal --add event=window_destroyed title!="^(|Fullscreen Controls)$" app!="^(Notification Centre|Raycast|Maccy)$" action="bash ~/.config/yabai/scripts/signals/window_destroyed.sh"
yabai -m signal --add event=window_minimized action="bash ~/.config/yabai/scripts/signals/window_minimized.sh"
yabai -m signal --add event=window_deminimized action="bash ~/.config/yabai/scripts/signals/window_deminimized.sh"
yabai -m signal --add event=space_changed action="bash ~/.config/yabai/scripts/signals/space_changed.sh"
yabai -m signal --add event=display_changed action="bash ~/.config/yabai/scripts/signals/display_changed.sh"

printf "yabai: configuration loaded...\\n"
