#!/bin/bash

# Define the target directory
TARGET_DIR="$HOME/Library/Application Support/Twitch Studio"

# Define the files to be symlinked
FILES=("hotkeys.json" "layouts.bak.json" "layouts.json")

# Loop through the files and create symbolic links
for FILE in "${FILES[@]}"
do

  # maiking the symbolic link
  ln -sf "$(pwd)/$FILE" "$TARGET_DIR/$FILE"

  # Check if the symbolic link was created successfully
  if [ -L "$TARGET_DIR/$FILE" ]; then
    echo "Symbolic link for $FILE created successfully!"
  else
    echo "Failed to create symbolic link for $FILE."
  fi
done

