os:
  editCommand: 'nvim -u ${MYVIMRCLSP} --listen $NVIM_SOCKET_DIR/nvim-$RANDOM.sock'
git:
  paging:
    colorArg: always
    pager: delta --paging=never
    # useConfig: true
promptToReturnFromSubprocess: false
