#!/usr/bin/env bash

# opens iTerm2
alt - return : "${HOME}"/.config/yabai/scripts/open_iterm2.sh
alt - q : \
    nextwinid=$(bash -c 'yabai -m query --windows --window east 2>/dev/null || yabai -m query --windows --window west 2>/dev/null' | jq -r .id) \
    bash -c 'yabai -m window --close && yabai -m window --focus $nextwinid'


# Show system statistics
fn + lalt - 1 : "${HOME}"/.config/yabai/scripts/show_cpu.sh
fn + lalt - 2 : "${HOME}"/.config/yabai/scripts/show_mem.sh
fn + lalt - 3 : "${HOME}"/.config/yabai/scripts/show_bat.sh
fn + lalt - 4 : "${HOME}"/.config/yabai/scripts/show_disk.sh
fn + lalt - 5 : "${HOME}"/.config/yabai/scripts/show_song.sh

# Navigation
alt - h : yabai -m window --focus west
alt - j : yabai -m window --focus south
alt - k : yabai -m window --focus north
alt - l : yabai -m window --focus east

# Move window to left and focus
cmd - space : yabai -m window --warp east; yabai -m window --focus west

# Shortcuts with hyper key

shift + cmd + alt + ctrl - h : yabai -m window --focus west
shift + cmd + alt + ctrl - j : yabai -m window --focus south
shift + cmd + alt + ctrl - k : yabai -m window --focus north
shift + cmd + alt + ctrl - l : yabai -m window --focus east
shift + cmd + alt + ctrl - q : yabai -m window --close
shift + cmd + alt + ctrl - return : "${HOME}"/.config/yabai/scripts/open_iterm2.sh
shift + cmd + alt + ctrl - space : yabai -m window --warp east; yabai -m window --focus west # Move window to left and focus
shift + cmd + alt + ctrl - 0x29 : "${HOME}"/.config/yabai/scripts/toggle_terminal_window.sh "Scratchpad" # Mapping semicolon(;) to open floating terminal
shift + cmd + alt + ctrl - n : "${HOME}"/.config/yabai/scripts/toggle_terminal_window.sh "Notes" "notetaker"
shift + cmd + alt + ctrl - r : kitty -1 --title "Bottom" -e $SHELL -lc "btm -b" & # Opens process monitoring tool
shift + cmd + alt + ctrl - m : kitty -1 --title "Ncmpcpp" -e $SHELL -lc "ncmpcpp" & # Opens music player
shift + cmd + alt + ctrl - p : mpc toggle # Toggle play/pause for mpd
shift + cmd + alt + ctrl - 0x21 : mpc seek -10 # Seek music 10 seconds backward with hyper + [
shift + cmd + alt + ctrl - 0x1E : mpc seek +10 # Seek music 10 seconds forward with hyper + ]
shift + cmd + alt + ctrl - 0x1B : osascript -e 'set volume output volume (output volume of (get volume settings)) - 10' # Volume down with hyper + -
shift + cmd + alt + ctrl - 0x18 : osascript -e 'set volume output volume (output volume of (get volume settings)) + 10' # Volume down with hyper + +

# Switch space, requires SIP to be disabled, handling the same with mac keyboard shortcuts for mission control
# alt - 1 : yabai -m space --focus 1
# alt - 2 : yabai -m space --focus 2
# alt - 3 : yabai -m space --focus 3
# alt - 4 : yabai -m space --focus 4

# Moving windows
shift + alt - h : yabai -m window --warp west
shift + alt - j : yabai -m window --warp south
shift + alt - k : yabai -m window --warp north
shift + alt - l : yabai -m window --warp east

# Move focus container to workspace
shift + alt - m : yabai -m window --space last; yabai -m space --focus last
shift + alt - p : yabai -m window --space prev; yabai -m space --focus prev
shift + alt - n : yabai -m window --space next; yabai -m space --focus next
shift + alt - 1 : yabai -m window --space 1; yabai -m space --focus 1
shift + alt - 2 : yabai -m window --space 2; yabai -m space --focus 2
shift + alt - 3 : yabai -m window --space 3; yabai -m space --focus 3
shift + alt - 4 : yabai -m window --space 4; yabai -m space --focus 4
shift + alt - 5 : yabai -m window --space 5; yabai -m space --focus 5
shift + alt - 6 : yabai -m window --space 6; yabai -m space --focus 6

# Resize windows
lctrl + alt - h : yabai -m window --resize left:-50:0; \
                  yabai -m window --resize right:-50:0
lctrl + alt - j : yabai -m window --resize bottom:0:50; \
                  yabai -m window --resize top:0:50
lctrl + alt - k : yabai -m window --resize top:0:-50; \
                  yabai -m window --resize bottom:0:-50
lctrl + alt - l : yabai -m window --resize right:50:0; \
                  yabai -m window --resize left:50:0

# Equalize size of windows
lctrl + alt - e : yabai -m space --balance

# Enable / Disable gaps in current workspace
lctrl + alt - g : yabai -m space --toggle padding; yabai -m space --toggle gap

# Rotate windows clockwise and anticlockwise
alt - r         : yabai -m space --rotate 270
shift + alt - r : yabai -m space --rotate 90

# Rotate on X and Y Axis
shift + alt - x : yabai -m space --mirror x-axis
shift + alt - y : yabai -m space --mirror y-axis

# Set insertion point for focused container
shift + lctrl + alt - h : yabai -m window --insert west
shift + lctrl + alt - j : yabai -m window --insert south
shift + lctrl + alt - k : yabai -m window --insert north
shift + lctrl + alt - l : yabai -m window --insert east

# Float / Unfloat window
shift + alt - space : \
    yabai -m window --toggle float; \
    yabai -m window --toggle border

# Restart Yabai
shift + lctrl + alt - r : \
    /usr/bin/env osascript <<< \
        "display notification \"Restarting Yabai\" with title \"Yabai\""; \
    launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"

# Make window native fullscreen
alt - f         : yabai -m window --toggle zoom-fullscreen
shift + alt - f : yabai -m window --toggle native-fullscreen
