"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]

prepend_keymap = [
  # Goto
  { on = ["g", "d"], run = "cd ${MY_DOTFILES_DIR}/.config" },
  { on = ["g", "D"], run = "cd ~/Downloads/" },
  { on = ["g", "P"], run = "cd ~/Pictures" },
  { on = ["g", "S"], run = "cd ~/Pictures/Screenshots" },

  # Shell
  { on = "$", run = 'shell --block $SHELL' },

  # Plugins
  #########
  { on = "M", run = "plugin mount" },
  { on = ["c", "m"], run = "plugin chmod", desc = "Chmod on selected files" },
  # Toggle
  { on = ["T", "p"], run = 'plugin toggle-pane min-preview' },
  { on = ["T", "P"], run = 'plugin toggle-pane max-preview' },
]
