#!/bin/bash
# Loads all tmux sessions in separate windows

source "$HOME/.local/bin/tmux/tmux-common-functions"

# Open tmux session if exist
tmux_sessions=$(tmux list-sessions -F "#{session_name}" 2>/dev/null)
session_icon_name_map=$(get_default_session_icon_name_map)

if [[ -z "${tmux_sessions}" ]]; then
    echo -e "No running tmux session found" >&2
    # Saving the session with tmux-resurrect
    if [[ -d "$XDG_CONFIG_HOME/tmux/plugins/tmux-resurrect" ]]; then
        echo -e "Restoring the session with tmux-resurrect..." >&2
        tmux start-server
        tmux new-session -d;
        if [[ -f "$XDG_CONFIG_HOME/tmux/hooks/resurrect-hook-post-restore-all" ]]; then
          # Path to the restore timestamp file
          timestamp_file="${XDG_CACHE_HOME:-$HOME/.cache}/tmux/restore-timestamp"

          # Initial timestamp before restoring
          initial_timestamp=$(date +%s)

          # Run the tmux-resurrect restore script if not configured to auto restore
          # bash "$XDG_CONFIG_HOME/tmux/plugins/tmux-resurrect/scripts/restore.sh"

          # Wait up to 10 seconds for the restore to complete
          for i in {1..10}; do
              if [[ -f "${timestamp_file}" ]]; then
                  restore_timestamp=$(cat "${timestamp_file}")
                  if (( restore_timestamp > initial_timestamp )); then
                      echo "Session loaded successfully."
                      break
                  fi
              fi
              sleep 1
          done

          # Check if the session was not restored within the time limit
          if (( i == 10 )); then
              echo "Session did not load within 10 seconds."
          fi
        else
          echo -e "Waiting for session to load..." >&2
          sleep 10
        fi
    fi
fi

tmux_sessions=$(tmux list-sessions -F "#{session_name}" 2>/dev/null)
if [[ "${tmux_sessions}" ]]; then
    for session_name in ${tmux_sessions} ; do
        actual_session_name=$(get_actual_session_name "$session_icon_name_map" "$session_name")
        echo -e "Terminal window name: $actual_session_name and tmux session name: $session_name" >&2
        openterm --title "${actual_session_name}" --shell "${SHELL}" --cmd-str "tmux a -t ${session_name}; ${SHELL}";
        sleep 1;
    done
else
    echo -e "No tmux session found at all" >&2
fi
