# WARN: experimental or [env] prepends mise installed binaries path to $PATH which sometimes takes precedence than the
# venv path, due to this virtualenv doesn't get activated in case of python
[settings]
# experimental = true
env_file = '.env'

[tools]
# https://mise.jdx.dev/registry.html#tools
python = "latest"
uv = "latest"
poetry = "latest"
node = "latest"
postgres = "latest"
redis = "latest"
aws-cli = "latest"
go = "latest"
rust = "latest"
lua = "latest"

# [env]
# _.file = '.env'
# MY_ENV = 'test'

# An external script file to be executed
# _.source = "./script.sh"

# https://mise.jdx.dev/hooks.html
# [hooks]
# enter = "echo 'I entered the project'"

# [hooks.enter]
# shell = "zsh"
# script = "eval $(poetry env activate)"

# [hooks.leave]
# shell = "zsh"
# script = "deactivate"
